# Copyright 2020 Tim Uding.
# Github profile: https://github.com/Timmy109
# Spigot Profile: https://www.spigotmc.org/members/_timmyy_.919057/
# Discord Server: https://discord.gg/wafV4VP

# Config version - Please don't touch this!
config-version: 1

# If a player report was successfully submitted, this message will be displayed in chat to the player
player-report-success: |-
  &8&l&m---------------------------------
  &a&lThank you! &aYour report has been submitted
  &a    Your reports help the community!
  &8&l&m---------------------------------

# If a bug report was successfully submitted, this message will be displayed in chat to the player
bug-report-success: |-
  &8&l&m---------------------------------
  &a&lThank you! &aYour report has been submitted
  &a    Your reports help the community!
  &8&l&m---------------------------------

# If a PLAYER report was successfully written to the file, notify staff with this message in chat
# You may use the {player} placeholder to get the reporter's name
staff-player-report-message: |-
  &8&l&m-----------------------------
  &c&l        NEW PLAYER REPORT
  &c&l      Submitted by: &7{player}
  &8     Check Discord for more details!
  &8&l&m-----------------------------

# If a BUG report was successfully written to the file, notify staff with this message in chat
# You may use the {player} placeholder to get the reporter's name
staff-bug-report-message: |-
  &8&l&m---------------------------
  &c&l        NEW BUG REPORT
  &c&l      Submitted by: &7{player}
  &8     Check Discord for more details!
  &8&l&m---------------------------

# Paste your Discord channel webhooks into the respective lines below
discord-bug-webhook-url: "https://discordapp.com/api/webhooks/752892179885850695/oVzQPYzwk5O2fhUv4nmpA70dPPHRPoBLrVgtFQBd6Tb4vdGeR8KBluG80CoQpOKy40up"
discord-player-webhook-url: "https://discordapp.com/api/webhooks/752892179885850695/oVzQPYzwk5O2fhUv4nmpA70dPPHRPoBLrVgtFQBd6Tb4vdGeR8KBluG80CoQpOKy40up"

# -----------------------------------------------------------------------------------
# Configuring the fields for the Discord webhook
# Follow this example:
#
# bug-report-fields:
#   1:
#    title: <title for the field>
#    content: <field content here>
#    inline: <true/false>
#
# Please note that Discord limitations mean that there can only be up to 25 fields!
# -----------------------------------------------------------------------------------

# Player report embed configuration
# Available placeholders: {player} (reporter), {report} (report content/bug)
bug-report-fields:
  1:
    title: "**Reports**"
    content: "Reported by: `{player}`"
    inline: false
  2:
    title: "Report Type"
    content: "Bug report"
    inline: false
  3:
    title: "Bug"
    content: "{report}"
    inline: false

# Player report embed configuration
# Available placeholders: {player} (reporter), {target} (reported player), {report} (report content/reason)
player-report-fields:
  1:
    title: "**Reports**"
    content: "Reported by: `{player}`"
    inline: false
  2:
    title: "Report Type"
    content: "Player report"
    inline: false
  3:
    title: "Reported Player"
    content: "`{target}`"
    inline: false
  4:
    title: "Reason"
    content: "{report}"
    inline: false

# Webhook embed colour
# Put a hex code (Including the #) into the respective lines below
# Make sure there are no spaces otherwise this may break!
discord-embed-bug-report-colour: "#F0FF00"
discord-embed-player-report-colour: "#C761DF"

