# BetterReports - BetterReports.java
#
# Plugin created by Timmy109
# Github profile: https://github.com/Timmy109
# Spigot Profile: https://www.spigotmc.org/members/_timmyy_.919057/
# Discord Server: https://discord.gg/wafV4VP
#
# MIT License
#
# Copyright (c) 2020 Tim Uding.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
# OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
name: BetterReports
version: 1.0.1
main: me.timmy109.betterreports.BetterReports
description: Reporting plugin with Discord webhook
commands:
  report:
    description: Report a player!
  reportbug:
    description: Report a bug!
  betterreports:
    description: Admin Command!
    aliases: br
permissions:
  betterreports.admin:
    description: Admin commands
    default: op
  betterreports.alerts:
    description: Receive report alerts
    default: op
  betterreports.reload:
    description: Reload the configuration
    default: op
