name: BetterReports
version: ${project.version}
main: me.timmy109.betterreports.BetterReports
description: Reporting plugin with Discord webhook
commands:
  report:
    description: Report a player!
  reportbug:
    description: Report a bug!
  betterreports:
    description: Admin Command!
    aliases: br
permissions:
  betterreports.admin:
    description: Admin commands
    default: op
  betterreports.alerts:
    description: Receive report alerts
    default: op
  betterreports.reload:
    description: Reload the configuration
    default: op
